// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    #[prost(message, optional, tag="1")]
    pub time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(bytes="vec", tag="2")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag="3")]
    pub events: ::prost::alloc::vec::Vec<EventBody>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventBody {
    #[prost(oneof="event_body::Event", tags="1, 2, 3, 4, 5, 6")]
    pub event: ::core::option::Option<event_body::Event>,
}
/// Nested message and enum types in `EventBody`.
pub mod event_body {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag="1")]
        LedgerUpdate(super::LedgerUpdate),
        #[prost(message, tag="2")]
        Funding(super::Funding),
        #[prost(message, tag="3")]
        ValidatorRewards(super::ValidatorRewards),
        #[prost(message, tag="4")]
        CWithdrawal(super::CWithdrawal),
        #[prost(message, tag="5")]
        CDeposit(super::CDeposit),
        #[prost(message, tag="6")]
        Delegation(super::Delegation),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Delegation {
    #[prost(bytes="vec", tag="1")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub validator: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
    #[prost(bool, tag="4")]
    pub is_undelegate: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CDeposit {
    #[prost(bytes="vec", tag="1")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub amount: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CWithdrawal {
    #[prost(bytes="vec", tag="1")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub amount: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub is_finalized: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Funding {
    #[prost(message, repeated, tag="1")]
    pub deltas: ::prost::alloc::vec::Vec<FundingDelta>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FundingDelta {
    #[prost(bytes="vec", tag="1")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub coin: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub funding_amount: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub szi: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub funding_rate: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidatorRewards {
    #[prost(message, repeated, tag="1")]
    pub validator_to_reward: ::prost::alloc::vec::Vec<ValidatorReward>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidatorReward {
    #[prost(bytes="vec", tag="1")]
    pub validator: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub reward: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LedgerUpdate {
    #[prost(bytes="vec", repeated, tag="1")]
    pub users: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, optional, tag="2")]
    pub delta: ::core::option::Option<LedgerUpdateDelta>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LedgerUpdateDelta {
    #[prost(oneof="ledger_update_delta::Delta", tags="1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20")]
    pub delta: ::core::option::Option<ledger_update_delta::Delta>,
}
/// Nested message and enum types in `LedgerUpdateDelta`.
pub mod ledger_update_delta {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Delta {
        #[prost(message, tag="1")]
        SpotTransfer(super::SpotTransfer),
        #[prost(message, tag="2")]
        CStakingTransfer(super::CStakingTransfer),
        #[prost(message, tag="3")]
        AccountClassTransfer(super::AccountClassTransfer),
        #[prost(message, tag="4")]
        InternalTransfer(super::InternalTransfer),
        #[prost(message, tag="5")]
        SubAccountTransfer(super::SubAccountTransfer),
        #[prost(message, tag="6")]
        Send(super::Send),
        #[prost(message, tag="7")]
        Deposit(super::Deposit),
        #[prost(message, tag="8")]
        Withdraw(super::Withdraw),
        #[prost(message, tag="9")]
        VaultDeposit(super::VaultDeposit),
        #[prost(message, tag="10")]
        RewardsClaim(super::RewardsClaim),
        #[prost(message, tag="11")]
        VaultWithdraw(super::VaultWithdraw),
        #[prost(message, tag="12")]
        VaultLeaderCommission(super::VaultLeaderCommission),
        #[prost(message, tag="13")]
        DeployGasAuction(super::DeployGasAuction),
        #[prost(message, tag="14")]
        AccountActivationGas(super::AccountActivationGas),
        #[prost(message, tag="15")]
        ActivateDexAbstraction(super::ActivateDexAbstraction),
        #[prost(message, tag="16")]
        Liquidation(super::Liquidation),
        #[prost(message, tag="17")]
        SpotGenesis(super::SpotGenesis),
        #[prost(message, tag="18")]
        VaultDistribution(super::VaultDistribution),
        #[prost(message, tag="19")]
        BorrowLend(super::BorrowLend),
        #[prost(message, tag="20")]
        VaultCreate(super::VaultCreate),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultCreate {
    #[prost(bytes="vec", tag="1")]
    pub vault: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub usdc: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub fee: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BorrowLend {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub interest_amount: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub operation: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultDistribution {
    #[prost(bytes="vec", tag="1")]
    pub vault: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub usdc: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpotGenesis {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub amount: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Liquidation {
    #[prost(string, tag="1")]
    pub liquidated_ntl_pos: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub account_value: ::prost::alloc::string::String,
    #[prost(enumeration="LeverageType", tag="3")]
    pub leverage_type: i32,
    #[prost(message, repeated, tag="4")]
    pub liquidated_positions: ::prost::alloc::vec::Vec<LiquidatedPosition>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LiquidatedPosition {
    #[prost(string, tag="1")]
    pub coin: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub szi: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActivateDexAbstraction {
    #[prost(string, tag="1")]
    pub dex: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeployGasAuction {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub amount: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultLeaderCommission {
    #[prost(bytes="vec", tag="1")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub usdc: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultWithdraw {
    #[prost(bytes="vec", tag="1")]
    pub vault: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="3")]
    pub requested_usd: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub commission: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub closing_cost: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub basis: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub net_withdrawn_usd: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RewardsClaim {
    #[prost(string, tag="1")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub token: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultDeposit {
    #[prost(bytes="vec", tag="1")]
    pub vault: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub usdc: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Withdraw {
    #[prost(string, tag="1")]
    pub usdc: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub nonce: u64,
    #[prost(string, tag="3")]
    pub fee: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Deposit {
    #[prost(string, tag="1")]
    pub usdc: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Send {
    #[prost(bytes="vec", tag="1")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub destination: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="3")]
    pub source_dex: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub destination_dex: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub usdc_value: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub fee: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub native_token_fee: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub nonce: u64,
    #[prost(string, tag="11")]
    pub fee_token: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubAccountTransfer {
    #[prost(string, tag="1")]
    pub usdc: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub destination: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InternalTransfer {
    #[prost(string, tag="1")]
    pub usdc: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub destination: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="4")]
    pub fee: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountClassTransfer {
    #[prost(string, tag="1")]
    pub usdc: ::prost::alloc::string::String,
    #[prost(bool, tag="2")]
    pub to_perp: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CStakingTransfer {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub amount: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub is_deposit: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpotTransfer {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub usdc_value: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="4")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub destination: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="6")]
    pub fee: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub native_token_fee: ::prost::alloc::string::String,
    #[prost(uint64, tag="8")]
    pub nonce: u64,
    #[prost(string, tag="9")]
    pub fee_token: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountActivationGas {
    #[prost(string, tag="1")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LeverageType {
    Unspecified = 0,
    Cross = 1,
    Isolated = 2,
}
impl LeverageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            LeverageType::Unspecified => "LEVERAGE_TYPE_UNSPECIFIED",
            LeverageType::Cross => "LEVERAGE_TYPE_CROSS",
            LeverageType::Isolated => "LEVERAGE_TYPE_ISOLATED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LEVERAGE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "LEVERAGE_TYPE_CROSS" => Some(Self::Cross),
            "LEVERAGE_TYPE_ISOLATED" => Some(Self::Isolated),
            _ => None,
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Fill {
    #[prost(bytes="vec", tag="1")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub coin: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub price: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub size: ::prost::alloc::string::String,
    #[prost(enumeration="FillSide", tag="5")]
    pub side: i32,
    #[prost(message, optional, tag="6")]
    pub time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="7")]
    pub start_position: ::prost::alloc::string::String,
    #[prost(enumeration="TradingDirection", tag="8")]
    pub direction: i32,
    #[prost(string, tag="9")]
    pub closed_pnl: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="10")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="11")]
    pub order_id: u64,
    #[prost(bool, tag="12")]
    pub crossed: bool,
    #[prost(string, tag="13")]
    pub fee: ::prost::alloc::string::String,
    #[prost(uint64, tag="14")]
    pub transaction_id: u64,
    #[prost(string, tag="15")]
    pub fee_token: ::prost::alloc::string::String,
    /// Time-Weighted Average Price Identifier
    #[prost(uint64, tag="16")]
    pub twap_id: u64,
    #[prost(bytes="vec", tag="17")]
    pub client_order_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="18")]
    pub liquidation: ::core::option::Option<FillLiquidation>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FillLiquidation {
    #[prost(bytes="vec", tag="1")]
    pub liquidated_user: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub mark_px: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub method: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FillSide {
    Unspecified = 0,
    Ask = 1,
    Buy = 2,
}
impl FillSide {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            FillSide::Unspecified => "FILL_SIDE_UNSPECIFIED",
            FillSide::Ask => "FILL_SIDE_ASK",
            FillSide::Buy => "FILL_SIDE_BUY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FILL_SIDE_UNSPECIFIED" => Some(Self::Unspecified),
            "FILL_SIDE_ASK" => Some(Self::Ask),
            "FILL_SIDE_BUY" => Some(Self::Buy),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TradingDirection {
    Unspecified = 0,
    Buy = 1,
    Sell = 2,
    OpenLong = 3,
    CloseLong = 4,
    OpenShort = 5,
    CloseShort = 6,
    LongToShort = 7,
    ShortToLong = 8,
    SpotDustConversion = 9,
    LiquidatedCrossLong = 10,
    LiquidatedCrossShort = 11,
    LiquidatedIsolatedLong = 12,
    LiquidatedIsolatedShort = 13,
    AutoDeleveraging = 14,
    Settlement = 15,
    NetChildVaults = 16,
    BackstopBorrowLiquidation = 17,
}
impl TradingDirection {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            TradingDirection::Unspecified => "TRADING_DIRECTION_UNSPECIFIED",
            TradingDirection::Buy => "TRADING_DIRECTION_BUY",
            TradingDirection::Sell => "TRADING_DIRECTION_SELL",
            TradingDirection::OpenLong => "TRADING_DIRECTION_OPEN_LONG",
            TradingDirection::CloseLong => "TRADING_DIRECTION_CLOSE_LONG",
            TradingDirection::OpenShort => "TRADING_DIRECTION_OPEN_SHORT",
            TradingDirection::CloseShort => "TRADING_DIRECTION_CLOSE_SHORT",
            TradingDirection::LongToShort => "TRADING_DIRECTION_LONG_TO_SHORT",
            TradingDirection::ShortToLong => "TRADING_DIRECTION_SHORT_TO_LONG",
            TradingDirection::SpotDustConversion => "TRADING_DIRECTION_SPOT_DUST_CONVERSION",
            TradingDirection::LiquidatedCrossLong => "TRADING_DIRECTION_LIQUIDATED_CROSS_LONG",
            TradingDirection::LiquidatedCrossShort => "TRADING_DIRECTION_LIQUIDATED_CROSS_SHORT",
            TradingDirection::LiquidatedIsolatedLong => "TRADING_DIRECTION_LIQUIDATED_ISOLATED_LONG",
            TradingDirection::LiquidatedIsolatedShort => "TRADING_DIRECTION_LIQUIDATED_ISOLATED_SHORT",
            TradingDirection::AutoDeleveraging => "TRADING_DIRECTION_AUTO_DELEVERAGING",
            TradingDirection::Settlement => "TRADING_DIRECTION_SETTLEMENT",
            TradingDirection::NetChildVaults => "TRADING_DIRECTION_NET_CHILD_VAULTS",
            TradingDirection::BackstopBorrowLiquidation => "TRADING_DIRECTION_BACKSTOP_BORROW_LIQUIDATION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRADING_DIRECTION_UNSPECIFIED" => Some(Self::Unspecified),
            "TRADING_DIRECTION_BUY" => Some(Self::Buy),
            "TRADING_DIRECTION_SELL" => Some(Self::Sell),
            "TRADING_DIRECTION_OPEN_LONG" => Some(Self::OpenLong),
            "TRADING_DIRECTION_CLOSE_LONG" => Some(Self::CloseLong),
            "TRADING_DIRECTION_OPEN_SHORT" => Some(Self::OpenShort),
            "TRADING_DIRECTION_CLOSE_SHORT" => Some(Self::CloseShort),
            "TRADING_DIRECTION_LONG_TO_SHORT" => Some(Self::LongToShort),
            "TRADING_DIRECTION_SHORT_TO_LONG" => Some(Self::ShortToLong),
            "TRADING_DIRECTION_SPOT_DUST_CONVERSION" => Some(Self::SpotDustConversion),
            "TRADING_DIRECTION_LIQUIDATED_CROSS_LONG" => Some(Self::LiquidatedCrossLong),
            "TRADING_DIRECTION_LIQUIDATED_CROSS_SHORT" => Some(Self::LiquidatedCrossShort),
            "TRADING_DIRECTION_LIQUIDATED_ISOLATED_LONG" => Some(Self::LiquidatedIsolatedLong),
            "TRADING_DIRECTION_LIQUIDATED_ISOLATED_SHORT" => Some(Self::LiquidatedIsolatedShort),
            "TRADING_DIRECTION_AUTO_DELEVERAGING" => Some(Self::AutoDeleveraging),
            "TRADING_DIRECTION_SETTLEMENT" => Some(Self::Settlement),
            "TRADING_DIRECTION_NET_CHILD_VAULTS" => Some(Self::NetChildVaults),
            "TRADING_DIRECTION_BACKSTOP_BORROW_LIQUIDATION" => Some(Self::BackstopBorrowLiquidation),
            _ => None,
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    #[prost(message, optional, tag="1")]
    pub block_header: ::core::option::Option<BlockHeader>,
    #[prost(message, repeated, tag="2")]
    pub fills: ::prost::alloc::vec::Vec<Fill>,
    #[prost(message, repeated, tag="3")]
    pub events: ::prost::alloc::vec::Vec<Event>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BlockHeader {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(message, optional, tag="2")]
    pub block_time: ::core::option::Option<::prost_types::Timestamp>,
}
// @@protoc_insertion_point(module)
